### ISSUE TITLE
Embedded language support is missing

### ISSUE THREAD

**Issue by yyx1111** [vsce-toolroom/vscode-textmate-languageservice#61]
In Vue, text interpolation cannot be resolved, such as `<span>Message: {{ abc.msg() }}</span>`, where `abc.msg()` cannot be parsed.

**Comment by zm-cttae** [comment]
Injections don't work in `vscode-textmate` but do work in VS Code.

**Comment by yyx1111** [comment]
> Injections don't work in `vscode-textmate` but do work in VS Code.

Is there no solution

**Comment by zm-cttae** [comment]
This does seem to be a new-ish feature (which the project isn't readily adding). But queries to Vue documents actually break because `source.stylus` isn't built into VS Code.
